#!/usr/bin/env python
"""
This code is part of the Arc-flow Vector Packing Solver (VPSolver).

Copyright (C) 2013-2016, Filipe Brandao
Faculdade de Ciencias, Universidade do Porto
Porto, Portugal. All rights reserved. E-mail: <fdabrandao@dcc.fc.up.pt>.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""
import sys

if __name__ == "__main__":
    from pyvpsolver import VPSolver
    assert len(sys.argv) in (2, 3)
    afg_fname = sys.argv[1]
    assert afg_fname.endswith(".afg")
    if len(sys.argv) == 3:
        svg_fname = sys.argv[2]
        assert svg_fname.endswith(".svg")
    else:
        svg_fname = afg_fname.rstrip(".afg")+".svg"
    VPSolver.afg2svg(afg_fname, svg_fname)
